#!/bin/sh

set -e
npm install

# Wait for database to start before migration scripts
./docker/wait-for-it.sh development-db.techladies.net:5432 

export NODE_ENV=development

set +e && npm run db:create 2> /dev/null && set -e 2> /dev/null
npm run db:migrate
set +e && npm run db:seed 2> /dev/null && set -e 2> /dev/null

npm run dev